### ISSUE TITLE
[DISCUSSION] Strategy to merge PRs 

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#170]
Right now there are 12 Open issues and 50 PRs. That means 4 fixes per issue.

1. How are we going to merge these PRs?
2. Will there be still PRs open after closing all the issues?

**Request to those who are submitting PRs:**

Before starting to work on an issue, claim the issue by saying "I am working on this". This will help duplication of effort.

**Request to those who are handling the repo**

1. Please provide a template for reporting issues
2. Please provide guidelines for PRs
3. A rough details of the back-end - like the db  CPU/RAM, available processing power for handling concurrent requests etc will be appreciated.
4. Expect a DDOS -  what is the mitigation strategy ?  (Expect the worst)

@biswaz @naveenpf - see this.

**Comment by manuvakery1** [comment]
#### Describe the bug :bug:
A clear and concise description of what the bug is.

#### Checklist
Put an `x` in the boxes that apply.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] I have assigned a `Label` for the issue (if applicable)


#### To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

#### Expected behavior
A clear and concise description of what you expected to happen.

#### Possible Implementation
Describe if ther any solution to this problem which you know.

#### Screenshots (if applicable)
Screenshots to help explain your problem.

#### Software (please complete the following information if the bug is related to specific versions of softwares):
| Software |  Version      |  Any other info  |
|:----------|:-------------|:------|
| NA |  NA | NA |

#### Additional context (if applicable)
Add any other context about the problem here.

**Comment by manuvakery1** [comment]
we could use the above template for raising issues

**Comment by bodhish** [comment]
@manuvakery1 this looks great, would be good to have template for raising issues.

**Comment by manuvakery1** [comment]
@bodhish you mean for PR ?

**Comment by midhunkrishna** [comment]
@bobinson We can also do a integration with Heroku [https://devcenter.heroku.com/articles/github-integration], for `auto-deploy` to test instances so that it would become easier to QA the PRs before merge. 
Anyone with a admin access to the main repo can do it. 

cc: @biswaz @manuvakery1

**Comment by manuvakery1** [comment]
@bobinson @bodhish   we can use this template for PRs
#### Description
Describe the big picture of your changes

#### Related Issue
Fixes #issue_no

#### Types of changes
Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
- [ ] :bug: Bug fix (non-breaking change which fixes an issue).
- [ ] :rocket: New feature (non-breaking change which adds functionality).
- [ ] :heavy_multiplication_x: Breaking change (fix or feature that would cause existing functionality to change).

#### Checklist
The following checklist should be checked on each new pull requests as well as the subsequent changes in the pull request.
Put an `x` in the boxes that apply. You can also fill these out after creating the PR.

- [ ] I have rebased the code with master(must).

#### What is the current behavior? (You can also link to an open issue here)


####  What is the new behavior (if this is a feature change)?


#### How was the fix tested?


#### If this PR introduce a breaking change, what changes might users need to make in their application due to this PR?


#### Screenshots (if appropriate)


#### Other information:

**Comment by bobinson** [comment]
@manuvakery1 midhunkrishna - there was a previous issue specific for the template but it was closed  (IDK why!).  Refer #99 

> @bobinson We can also do Heroku integration, for auto-deploying test instances so that it would become easier to QA the PRs before a merge.

CI is a good idea @midhunkrishna

**Comment by salmanulfarzy** [comment]
#62 and #104 proposed issue and PR templates with related issue on #99, But was closed on https://github.com/IEEEKeralaSection/rescuekerala/issues/99#issuecomment-413552836 by @naveenpf with 

> Not required

Hope @naveenpf reconsiders the decision to control and channel issues and PRs.

**Comment by midhunkrishna** [comment]
In the case of DDOS @bobinson, these are the ones we usually follow:
1. Throttle the requests say with something like https://github.com/jsocol/django-ratelimit
2. Combine the one with geolocation based limiting, can help (Cloudflare offers a free tier I suppose)

thinking out loud here.

**Comment by cibingeorge** [comment]
@bobinson do you hve infrastructure scaling issues?

**Comment by bobinson** [comment]
@cibingeorge - sluggish. @biswaz @naveenpf  : please talk to either @dileep-p or @cibingeorge  on infra. They have tons of experience with large scale infrastructure.

**Comment by abhn** [comment]
It already seems to be using Cloudflare @midhunkrishna Maybe set rate limiting/security level on the Cloudflare admin. At this point, even basic Cloudflare protection should prevent ddos at the expense of displaying random captchas to unsuspecting users.

**Comment by bobinson** [comment]
Thanking everyone for the inputs.
