### ISSUE TITLE
Current map may cause loading issues very soon

### ISSUE THREAD

**Issue by iamvajid** [IEEEKeralaSection/rescuekerala#233]
### Subject of the issue
Current mapping implementation may face bottlenecks if more data comes in. Either we should filter to reduce the data size or put data to tile-based mapping solutions, for eg, cartoDB is a quick one and has free tier. Let me know if you need any help. The map aggregation and heatmap feature will help to identify the intensity and various other visualizations. It wil be really helpful.

### Steps to reproduce
If more data is loaded, this may happen very soon causing issue to render huge number of points on the map

### Expected behaviour
Maps should load smoothly

### Actual behaviour
it takes time to render the data on the map

**Comment by vigneshhari** [comment]
we are  trying to reduce the number of pins , we have a different repo for detailed map related queries

**Comment by vigneshhari** [comment]
https://github.com/aswinmohanme/kerala-flood-map

**Comment by ajitsen** [comment]
We might have to show critial ones at zoomed out level

**Comment by iamvajid** [comment]
hi @vigneshhari , reducing the number pins means compromising on the data right ? I have a map on carto which loads in 2-3 seconds with 50k+ data. Tile-based maps seems the way to go, until unless there is a better solution.

**Comment by answerquest** [comment]
Can change to using leaflet's circleMarker (SVG) instead of the traditional icon, then you can have as many markers as you want. See: https://github.com/aswinmohanme/kerala-flood-map/issues/10#issuecomment-413660368 (pls ignore my first post there, was saying divicon by mistake) . I've shared snippets of how to make it work in vanilla leaflet js. I can't get my head around the react-leaflet framework, it's like a totally new language.

**Comment by aswinmohanme** [comment]
Currently we have a production build waiting merge with MarkerCluster and client side filtering, it has improved the performance very much, and when the circle marker fix lands it would improve
