### ISSUE TITLE
[Discussion] Making sense of the data

### ISSUE THREAD

**Issue by biswaz** [IEEEKeralaSection/rescuekerala#240]
We have the largest dataset of the flood. We should be able analyse it to make a find information like
What kind of needs are more for a district
Where are the most number of rescue requests coming from
Which district have volunteers registered with medical expertise
etc...

**Comment by irshadshalu** [comment]
Wasn't there a CSV export option being developed?.

**Comment by biswaz** [comment]
you can find a subset on /data

**Comment by kannankumar** [comment]
I used the data at https://keralarescue.in/data/ to analyze the data.
Things i tried to answer:
1) Where are most requests coming from?
![image](https://user-images.githubusercontent.com/711743/44233688-36357300-a1c2-11e8-8265-4092a7b0f5ca.png)
2) What kinds of needs are most per district
![image](https://user-images.githubusercontent.com/711743/44233722-4a797000-a1c2-11e8-98e1-ce9a3fa4c042.png)

3) Volunteer expertise per district.
I'm looking for the volunteer data. If you could point me to it, I could look into it as well.

End Goal: to convert these analysis into a live dashboard

**Comment by biswaz** [comment]
This is the rescue request subset

**Comment by Neonkraft** [comment]
How are we planning on filtering out stale data?

**Comment by kannankumar** [comment]
alright, could you point me to the volunteer details if available?
It would be useful to proportionately map volunteers counts to requests or urge for more volunteers in districts which lack volunteers.

**Comment by kannankumar** [comment]
Im filtering Requests with "New" status. 
As of now, I see only "New" Status in the data.

<img src="https://user-images.githubusercontent.com/711743/44234042-3124f380-a1c3-11e8-8440-9346918f9007.png" width="300px"/>

**Comment by lunaroyster** [comment]
There's a problem, and I'm not sure where to write about it. As of right now, there are 2746 requests for help on this: https://keralarescue.in/data/

It's obvious that they are of varying urgency. I'm currently looking through random submissions, and occasionally I find something like this: 
![image](https://user-images.githubusercontent.com/6189367/44235168-39caf900-a1c6-11e8-811e-90d4c6310015.png)

We need a way to determine the urgency of these requests. 

1. We could try looking for keywords like 'Urgent', 'Pregnant', 'Trapped', 'Infant' et cetera, and use those to determine urgency.
2. Another idea is to crowdsource urgency. Let's have people vote on the apparent urgency of requests.

This way, we could help rescuers find the people with urgent needs first.

**Comment by kannankumar** [comment]
1) One way to do Idea 1  automatically would be tokenize the free text strings like "detailRescue" to search for keywords like "Urgent", "Pregnant", "Baby","Elderly", "Medical help", etc and give it a higher priority based on the count of people in those strings.

2) Alternatively, If we have people available to sift through the requests and vote/flag them that would be fine for now. The flag should be clearly visible to the rescue team next to the requests on the site.

**Comment by kannankumar** [comment]
Hourly breakdown of requests coming in from different districts gives an idea of where situation got worse first or is getting worse.
<img src="https://user-images.githubusercontent.com/711743/44236761-bdd3af80-a1cb-11e8-920b-7942aaf3ec51.png" width="700px"/>

**Comment by anandkp92** [comment]
Adding the code and the csv files for "Urgent", "Pregnant", "Baby","Elderly","medic". 

[separated-based-on-urgent-pregnant-etc.zip](https://github.com/IEEEKeralaSection/rescuekerala/files/2295625/separated-based-on-urgent-pregnant-etc.zip)

**Comment by msrajesh** [comment]
Could see  duplicate  in the above csv .  Is   the duplicate  requests  handled manually  by  the rescue team ?

**Comment by kannankumar** [comment]
@anandkp92 - I had a look at your notebook. It works well to give a filtered list based on category.However count of people in a single msg is also an important information that I feel determines urgency.
(Eg - A hospital near Aluva with 26 Bed ridden  patients, 15 kids, and 20 nuns)

Idea: We can flag urgency based on category(Adults, Kids, Elderly, etc) and Counts of people. 

Parsing the detailrescue for counts is proving cumbersome. It would help if we have fields for how many Adults, Kids, Elderly, Pregnant, etc when filling in request field?

**Comment by criscod** [comment]
I just realised that the values in column 'latlng_accuracy' vary in their format. It can contain, for example:
* A float or integer and the word "Meters" (e.g., ``` 2400 Meters``` or ```98.4000015258789 Meters````
* The word "accurate"
* A new coordinate with parentheses (e.g., ```(10.1099392,76.3286127)```)
* A Google Maps URL 

In the last two cases, should this field be used for the position rather than the 'latlng' field?

How is the data collected?

**Comment by irshadshalu** [comment]
@criscod The discrepancies in data is caused by making the GPS and Accuracy Field editable for a short time. (Users could enter almost anything as mentioned in #225 . This was fixed later and a PlacePicker is being implemented.

**Comment by criscod** [comment]
Great to hear that. Thanks for the info :)

**Comment by criscod** [comment]
It is possible to query [Wikidata](https://www.wikidata.org/) and visualize in a map types of Points of Interest around the coordinates in the rescue requests. See the map I generated with this query as an example: 
```SELECT ?place ?location ?distance ?placeLabel ?type ?typeLabel ?layer WHERE {
    SERVICE wikibase:around { 
      ?place wdt:P625 ?location . 
      bd:serviceParam wikibase:center "Point(76.3230197 10.0021295)"^^geo:wktLiteral .
      bd:serviceParam wikibase:radius "5" . 
      bd:serviceParam wikibase:distance ?distance .
    } 
    ?place wdt:P31 ?type .
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". ?type rdfs:label ?layer }
} ORDER BY ?distance LIMIT 100
````
(Query executed at: ```https://query.wikidata.org/```).

Would this be of any help, if we create map visualizations that show e.g., schools, malls, metro stations to concentrate any help action around these places? 

![image](https://user-images.githubusercontent.com/3739519/44266195-e9858280-a229-11e8-8819-1ababb09b62b.png)

**Comment by anandkp92** [comment]
@kannankumar I agree, I've raised an issue to have a field to input approx number of people at location. More than urgency, it might help planning the evacuation

**Comment by ManuGMathew** [comment]
Hi all, I just came across this discussion. If it helps, the number of days they have been stuck on a rooftop would be an important factor to determine urgency. if we use the notebook code given by @anandkp92 to search for "days" in the description field, we end up with 2 kinds of entries. 
a. People stuck in a place since N days. (This group would be close to running out of provisions if any)
b. N day old baby present in the group.
Both these scenarios would push up the urgency.

**Comment by dipine** [comment]
Maybe clustering with a decision tree will help to better serve them.
Step 1. Clustering people based on number of days (N1Cluster)
Step 2.  Group Clusters(N1Cluster) which are nearby (geofencing with radius x km) will speed up the process

Decision Tree -> running which clusters has to be given high prioritises by (medic,food, airlift) so that each further nodes we can serve critical; mean while giving others supplies (food& water) there by prioritises are always higher for who actual is in high alert critical.

**Comment by binithb** [comment]
Does this requirement ( making sense of data) need to be on the same website/platform(keralarescue.in itself) or can it  be on a different platform? I mean it will be good to have everything on the same platform but then it might be easier to export this data on other tools and generate whatever visualizations we need..

**Comment by amalmurali47** [comment]
@binithb I don't think it needs to be on the same platform. The data analysis can be carried out on a different machine/server/platform, and after processing the data, the results can be presented on the website.

**Comment by lunaroyster** [comment]
@binithb I think a closely developed network of tools is a good idea for these kind of projects.

I've created a [website](http://kerala-crowdsource.itsarnavb.me) that's trying to categorize requests from keralarescue.in on the basis of their urgency. Creating a separate project is a good idea, since you can move faster and roll out new features quickly.

**Comment by binithb** [comment]
![image](https://user-images.githubusercontent.com/1933844/44290921-6856db80-a27b-11e8-9b19-803af8c2a069.png)

That's a quick prototype of what can by done using Tableau public. It can also be embedded on web pages. I am assuming data privacy is not a concern right now. If this is good enough and there are no other concerns we can discuss how to get this data automatically. This prototype is created from data in a static json file that I downloaded from /data

**Comment by sarathsasidharan** [comment]
@binithb , would it not be the case to ask the rescue teams to mark the field as done which will help us to filter better  since there are many districts where people are stuck for multiple days , so that approach of filtering on the present day could be a problem

**Comment by lunaroyster** [comment]
@sarathsasidharan yes. There's already a field called status on the data at keralaresuce.in/data. It doesn't appear as if it's being used: 
![image](https://user-images.githubusercontent.com/6189367/44298696-40ac5580-a305-11e8-9db8-5e99c238ae27.png)
 
Most still say 'new'.

**Comment by sarathsasidharan** [comment]
Would it be possible to automatically update this flag to completed/processing as soon as it picked up by the authority , so in this case we dont depend on them to change this to completed , so on click by agent -->change the flag to processing

**Comment by sarathsasidharan** [comment]
Latest summary from the sample , but with a few blanks for the districts for newly introduced status types
![image](https://user-images.githubusercontent.com/9977936/44299570-4ef47480-a2f9-11e8-9a03-d6b0eb65b8b5.png)

**Comment by ssat335** [comment]
Shall we try work on https://processkeralarescue.herokuapp.com/

I have created a repo in https://github.com/ssat335/processkeralarescue

**Comment by ankithjoseph** [comment]
#617

**Comment by kannankumar** [comment]
@ssat335  -The plotly app looks good as a quick interface for officials to look at.

What are the other things we can to the site? 
If we could group the data based on city instead of just District level that would be give a more granular info for the relief materials to reach correct locations. 
eg - In Allapuzha district, how much request is coming from Chengganur and Thiruvalla, etc.

Will it be possible to do some form of preprocessing on the latlng or location details before plotting using plotly??

**Comment by kannankumar** [comment]
@lunaroyster - I liked the quick Urgent request filtering app you created. 
"I've created a website that's trying to categorize requests from keralarescue.in on the basis of their urgency. "  
How are you categorizing urgency?? I'm asking because keralafights.com is trying to crowdsource urgent request categorization by volunteers marking a request as urgent or not. If your approach is automated, that might provide a first level filtering to volunteers.

**Comment by ssat335** [comment]
@kannakumar yes, prepro essing of the lats and lon can be possible. Please see the repo for some existing issues and we may start from there.

**Comment by lunaroyster** [comment]
>keralafights.com is trying to crowdsource urgent request categorization by volunteers marking a request as urgent or not

That's exactly what I've done. I'm providing several levels of urgency. The same requests are shown to several people, and I use wilson score (takes into account the number of votes) to determine urgent requests.

I'm working on categorizing new requests as soon as they arrive. I think it'll make sense for keralafights.com to integrate the crowdsourcing tool at https://kerala-crowdsource.itsarnavb.me, since we've already got ~11K datapoints. 

I'm not sure how effective automated approaches are. I think people have tried NLP, but the data is pretty noisy.

**Comment by lunaroyster** [comment]
I'd love to get in touch with the keralafights.com folks. Reach me at https://twitter.com/itsarnavb

**Comment by kannankumar** [comment]
@lunaroyster Yes you are right, the free text fields lead to very noisy data which is proving difficult to clean using NLP scripts. Manual intervention is required to sift through the 11K datapoints.
Wilson score is credible if there are more number of votes.

However the integration details can only be clarified by others. Since you've already got a site up and running with Wilson score for urgency ranking,  why not post it on slack and get people to discuss integration options.

**Comment by kannankumar** [comment]
Im not sure who is working on keralafights.com but you could check with them here:
**"for any feedback on changes / data / api please mail your feedback to keralafights@ceegees.in"**

**Comment by lunaroyster** [comment]
Yep, I'm talking to the keralafights folks right now.

I want to integrate with the keralarescue.in database. I've already got an endpoint with the urgency results here: https://us-central1-keralarescue-fef8e.cloudfunctions.net/getUrgencies

Also, the /data endpoint was taken down. I know it was a heavy load, and I was using excessive caching on my end to not burden the keralarescue servers.

I really need that endpoint for the crowdsourcing application.

**Comment by binithb** [comment]
I made some visualizations hosted at http://206.189.139.183:8000/stats/requests and http://206.189.139.183:8000/stats/volunteers

sample screenshot - 
![image](https://user-images.githubusercontent.com/1933844/44309959-f68fa680-a3ce-11e8-81a9-0361a1af759c.png)

Some of the charts are interactive. 
I havent raised a pull request for this yet. Please comment if this is inline with what we are looking for.
(The data is from an sqldump I received this morning)

**Comment by IkbenJee** [comment]
@kannankumar are you connecting to a live data source?

**Comment by binithb** [comment]
I also saw some excel based data being shared around. If that's too much of a hassle that kind of work also can be done using this (read only, not for editing) provided the data is in a database/dump

**Comment by IkbenJee** [comment]
Guys, i have been able to extract the data from sql reports and have created a visual, you all can access it from Tableau public.

Since its an extract a lot of time is spent on cleaning the data, if you can let me know, how i can connect to a live dashboard, we can try to make a live connection.

I have set few filters on the dashboard, based on date, medical help required and location.

The phone number, the latitude and longitude columns requires some cleaning, because its mixed with text data, so tableau is unable to read it as a dimension.

https://public.tableau.com/profile/jithesh4829#!/vizhome/MissionKeralaRescue/MissionKeralaRescue?publish=yes

Let me know, if i can be of any help.

All the best, JCK

**Comment by kannankumar** [comment]
@binithb No I'm not connecting to the live data source. The keralarescue.in/data endpoint is Out of Bounds , Limited at 300 records and only used for /map. 
I got a database dump from @lunaroyster yesterday . They are working on crowdsourced urgency mapping at (https://kerala-crowdsource.itsarnavb.me) 

It would be awesome if we keep pushing DB dumps to Json every few hours for data guys to explore and derive insights.

<img width="767" alt="requested help by districts" src="https://user-images.githubusercontent.com/711743/44318670-1c5f8e80-a455-11e8-8c74-f2c56d56f3b5.png">
****Hourly Requests per District (as of 5pm, 19th Aug) PS-Open image in new tab for clear view****

**Comment by naveenpf** [comment]
we should be doing that hourly in both csv and json 
And keep it on right top corner of this page. 
https://keralarescue.in/requests/?district=

**Comment by binithlighting** [comment]
@IkbenJee Nice dashboard. Once there is decision on whether or not we have live access to DB we can work together. If the decision is to only work based on offline dumps I can setup another postgres DB and share you access.
The t/f you are referring to must be true/false values(boolean). They should be readily populated with correct type if you are connecting to the live table. It must be because you are working with text data that you are seeing these t/f values

There is also the question about Tableau licensing. I think once we have confirmation that this approach is useful perhaps we can request for a charity/non profit license from Tableau foundation.

**Comment by IkbenJee** [comment]
@binithlighting ! Yes, If I am able to connect to the data dump also, it would be handy.

The dashobard is ofany use, if the information is UPTO date and have a normal refresh schedule with the latest status. Otherwise no point in working on something like this.

Question: How are we going to roll this out a wide coummunity? I know we can publish it to Tableau and people can access this using a url.

I hope the idea is not to create a fancy dashboard, but a dashboard to get all information as possible, we can also provide direct links on the dashboard to emergencies and other sources. 

Its easy to develop any viz, if we have a clean data.

I can also reach out to wider tableua community, if we need any help! or create a challenge to deveop dashboard like they have teh " # DEAR DATA TWO".

 All the best!

**Comment by binithb** [comment]
@IkbenJee  I made the mistake of last comment using my official account (@binithlighting ). Please use the handle @binithb if you need to contact me

**Comment by girishkurup** [comment]
[Work done so far in visualization.docx](https://github.com/IEEEKeralaSection/rescuekerala/files/2305721/Work.done.so.far.in.visualization.docx)
Please finalize the Tools and Graphics for different metrics and Who is the owner for each metrics/graphics
