### ISSUE TITLE
Requesting for others still sends GPS coords of user

### ISSUE THREAD

**Issue by biswaz** [IEEEKeralaSection/rescuekerala#248]
### Subject of the issue
Selecting requesting for others still sends the current users GPS coordinates to the server

### Steps to reproduce
Goto /requests and select requesting for others. Fill other details and send. 

### Expected behaviour
Should not send any gps coordinates

### Actual behaviour
DB will have the gps coordinate of the current user

**Comment by irshadshalu** [comment]
Can be solved by 

```$('#id_latlng').val('');
$('#id_latlng_accuracy').val('');```

Inside 
```if(checkboxElem.checked){

}```


Don't have access to lap right now, someone fix it.

**Comment by a-thomas-ny** [comment]
What about existing data. Anyway to cleat outside Kerala coordinates?

**Comment by bobinv001** [comment]
Tested it locally by ticking and unticking the "id_is_request_for_others" field, can confirm that the inputs are cleared

**Comment by bobinson** [comment]
I haven't tested this but, something like the following is apt.

We should not be disabling the GPS when someone else is entering the data. We should just prevent it from fetching the current location. This is because in multiple cases we are getting GPS locations of people to be rescued.

![image](https://user-images.githubusercontent.com/18070249/44245138-ede37880-a1f4-11e8-94fd-807ffbb3df80.png)

**Comment by bobinson** [comment]
#236 #232  - there are multiple fixes.

**Comment by ashwinkjoseph** [comment]
Guys can you take a look at #266

**Comment by ashwinkjoseph** [comment]
@bobinson this is exactly whats being done in #266
