### ISSUE TITLE
manually added location is getting saved in others needs field

### ISSUE THREAD

**Issue by ashwinrajeev** [IEEEKeralaSection/rescuekerala#528]
### Subject of the issue
Input field for location is `needothers`

<input type="text" name="needothers" maxlength="500" class="form-control" placeholder="Enter location manually" title="" id="pac-input">

### Steps to reproduce
* add location manually.
* check newly created request

### Actual behaviour
location data is getting saved in wrong field

**Comment by vishal-nayak** [comment]
@ashwinrajeev are you working on fixing this?

**Comment by ashwinrajeev** [comment]
@vishal-nayak no

**Comment by vishal-nayak** [comment]
Alright, I'm working on this

**Comment by msrshahrukh100** [comment]
@vishal-nayak are you working on this, it was a bug from myside, just remove the name attribute form the placepicker_form.html

**Comment by vishal-nayak** [comment]
I have validated the issue. 
#### Case 1: Add GPS based location with `Other Needs` data.
- Expected Behavior: `lt lng` and `needothers` to be populated
- Observed Behavior: `needothers` not populated

#### Case 2: Add location manually with `Other Needs` data.
- Expected Behavior: `lt lng` and `needothers` to be populated
- Observed Behavior: `needothers` populated with Manual Location input field value

Discussed with @msrshahrukh100, and he will be raising a PR for this.
