### ISSUE TITLE
damage assessment form - fields

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#946]
### Subject of the issue
Describe your issue here.

### Your environment
iOS (version to be defined)
Android Kitkat+

### Expected behaviour

Changes requested by KSITM on Disaster Assessment form. 

1. move the ward no before house no

2. XLS containing village taluk etc, shared can it be added in a drop-down fashion
Add village and taluk fields as drop-downs
3. Local body along with district, taluk, village, Panchayat, block etc if fields are not there pls add, and make them the first fields, so that can be filled first before collecting bldg details

4. in the secondary category add one  more option general
5. remove fields total no of family members, no of adults, no of children
6. Option to add 3 photos, medium quality
7. Date and time also is not coming automatically

**Comment by bobinson** [comment]
1.  ~move the ward no before house no~

![image](https://user-images.githubusercontent.com/18070249/44622035-79809780-a8ce-11e8-8c73-1242195c36ab.png)




> 2. XLS containing village taluk etc, shared can it be added in a drop-down fashion
Add village and taluk fields as drop-downs

Adding the dropdown completion is not going to be a possibility without affecting offline and performance of the app, that is too many fields.

3. TODO

4. ~in the secondary category add one more option general~

![image](https://user-images.githubusercontent.com/18070249/44622052-b8aee880-a8ce-11e8-89d4-6b42225710ca.png)

5. ~remove fields total no of family members, no of adults, no of children~

**Comment by ntsreejith** [comment]
Date and Time is by default pointing to GMT and then need to scroll to IST

![screenshot_2018-08-26-08-43-01-099_com ushahidi mobile](https://user-images.githubusercontent.com/42038063/44624435-75736a80-a90c-11e8-8c76-5fbca3193719.png)

**Comment by naveenpf** [comment]
Adding the dropdown completion is not going to be a possibility without affecting offline and performance of the app, that is too many fields.

This is very for govt @bobinson 
We need taluk and village, lsg type(if type) , LSG Name and Ward to be drop down.
Otherwise pulling report will be ugly. 

We didnt implement in govt relief camps. See what happened. tcr has only 7 taluk.
https://keralarescue.in/dmotal/?district=tcr
Same in case all district. 

We have implemented drop down for LSG in private relief camps and collections centre from the data from LSG election site. http://lsgelection.kerala.gov.in
1. https://keralarescue.in/collection_center/
2. https://keralarescue.in/pcampadd

Even if we have hit in offline performance we need to implement it .
If we cant implement this, I think this is a show stopper in govt context.

**Comment by muneebkattody** [comment]
Completed?
